apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: db
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: db
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: mydatabase
        - name: POSTGRES_PASSWORD
          value: mypassword
        - name: POSTGRES_USER
          value: mydatabaseuser
        image: postgres
        name: db
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: backend
  name: backend
spec:
  type: NodePort
  ports:
    - name: "8000" 
      port: 8000
      nodePort: 31000
  selector:
    app.service: backend
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.service: backend
  name: backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app.service: backend
    spec:
      containers:
      - env:
        - name: SECRET_KEY
          value: "quelargoesto"
        image: eu.gcr.io/river-autumn-252317/moni-test/moniback
        name: backend
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: frontend
  name: frontend
spec:
  type: NodePort
  ports:
    - name: "3000" 
      port: 3000
      nodePort: 32000
  selector:
    app.service: frontend
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.service: frontend
  name: frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app.service: frontend
    spec:
      containers:
      - env:
        image: eu.gcr.io/river-autumn-252317/moni-test/monifront
        name: frontend
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
